### ISSUE TITLE
Update method to display supported bills

### ISSUE THREAD

**Issue by soarhevn** [ACTtaiwan/CongressionalGuide#16]
Update the method used to display the supported bills (see red box in the screenshot below) to use the bills.json information. Show a candidates support if they are a sponsor or cosponsor.

![image](https://cloud.githubusercontent.com/assets/4950976/17081544/82848f14-5112-11e6-8b39-5c77f57f6a3f.png)

[bills.json.txt](https://github.com/ACTtaiwan/CongressionalGuide/files/380091/bills.json.txt)

**Comment by soarhevn** [comment]
Looks like the only real way to do this is via a json file. Saved as bills.json.

Query
https://congress.api.sunlightfoundation.com/bills?apikey=[key]&bill_id__in=sconres38-114|hconres88-114|s2426-114|hr4154-114|hr1853-114|hconres76-114|s1683-113|hres494-113|hjres109-113|sjres31-113|hconres55-113|hconres46-113|hr1151-113|s579-113|hres185-113|hconres29-113|s12-113|hr419-113&fields=official_title,urls.congress,sponsor_id,cosponsor_ids

**Comment by balamark** [comment]
@terry77228 東東 bill data is in our database table now!  
The existing table schema actually make lot of sense, so I filled the data in accordingly. When you want to know which bill does a candidate support, do 
`SELECT bioguideId FROM candidates WHERE state = 'WA' and district = 1;`
**D000617**
`SELECT billId FROM cosponsors_bills WHERE cosponsorId = 'D000617';`
**hr1853-114**
`SELECT officialTitle FROM bills WHERE billId = 'hr1853-114';`
**To direct the President to develop a strategy to obtain observer status for Taiwan in the International Criminal Police Organization, and for other purposes.**

幾爸分 💯

**Comment by balamark** [comment]
@soarhevn take a look for the PR, and once it merge Tung can render it to the page. 💃

**Comment by soarhevn** [comment]
@terry77228 let me know when you are ready on the page rendering for this. Thanks!
