### ISSUE TITLE
Create Name Mapper for use with Ballotpedia

### ISSUE THREAD

**Issue by soarhevn** [ACTtaiwan/CongressionalGuide#17]
If we want to use https://ballotpedia.org as the data source, we need to reverse engineer and write a valid name mapper to map the name stored in our database to the url format in ballotpedia.

Candidates are /[name] i.e. https://ballotpedia.org/Ron_Crumpton

This issue is required to be completed before Issue #6

**Comment by richmengsix** [comment]
I don't think this is required anymore as Mark decided to take another approach. He can explain more in detail.
