### ISSUE TITLE
Candidates data integration

### ISSUE THREAD

**Issue by MeowMeowMeowMeowMeowMeowMeowMeow** [ACTtaiwan/CongressionalGuide#20]
Integrate candidate data collected from #6.

**Comment by jtsaich** [comment]
the best way to map the scrapped data to the data in db seems to be using first and last name. The latest db has that info and has proper upper, lower cases. There are some names that might not work well (for candidates that fill their name with prefix or suffix, ex: Dr., Jr.), but I think we should be able to map the majority of data together.

**Comment by balamark** [comment]
hey HW, I wrote a script to dump the json data into sqlite3. I will send a pull request now. We still need to add the new column 'img_src' in the current 'candidates' table schema for the script to work.

**Comment by balamark** [comment]
Once database have all candidates data, some files utilized db probably needs to update, too. for example: app/routes/candidates.js.

**Comment by soarhevn** [comment]
Match between Sunlight & web-scrape of Ballotpedia: Last name, first word of given name, state, office_district.

Note that for office_district, "00" means Senate. So for Ballotpedia data, simply mark candidates for Senate as "00" for office_district when storing to the db.

**Comment by soarhevn** [comment]
@balamark this one is not quite done yet, right?

**Comment by balamark** [comment]
there is two issue left here:
1) after we looked at the page on Sunday, these 5 states' primary election is not occur yet. Hence, their page layout is different. We can either manually lookup xpath for all candidates for these states (which is not so hard, probably take an man-hour) or we wait after primary election happen for those states and use spider2.
2) just found that there are only 33 states data for senate on ballotpedia (https://ballotpedia.org/United_States_Senate_election_in_Alabama,_2016).

**Comment by soarhevn** [comment]
On the states left for the primary, let's just leave it, and it will start working correctly after Aug 30 right? I'll look up those states and put a note about it on the page. 

For the senate missing some states, those states may not have any open races for senate seats. Remember it's staggered and 6 year office, so this means 1 out of every 3 elections that are every two years for each state will not have an open senate race.
