### ISSUE TITLE
Email questionnaire is too long to be available for all email clients

### ISSUE THREAD

**Issue by terry77228** [ACTtaiwan/CongressionalGuide#29]
Regarding to [Issue 14](https://github.com/ACTtaiwan/CongressionalGuide/issues/14)
The content of Email questionnaire is too long to be available for all email clients.

**Comment by soarhevn** [comment]
Reduced text to under 1,400 characters, which should work for 95% of situations. May not work in very old browsers or email clients such as Outlook Express.

Commit: origin/#29Email_questionnaire_too_long
