### ISSUE TITLE
Candidate List Display

### ISSUE THREAD

**Issue by soarhevn** [ACTtaiwan/CongressionalGuide#3]
See wiki [here](https://github.com/ACTtaiwan/CongressionalGuide/wiki/UX-Mockups#candidate-list) for more info.

**Comment by cheweich** [comment]
Pushed some basic layout changes for displaying incumbent and challengers, lacking bill and questionnaire section. 

https://github.com/ACTtaiwan/CongressionalGuide/commit/bdba099114fbbf8dc4c8a0c32119f581680a2b94

**Comment by soarhevn** [comment]
陳韻如 is the UX. Facebook: yunju.chen.927

**Comment by soarhevn** [comment]
Any ETA on completion?

**Comment by soarhevn** [comment]
Tung-tung is actively working on this now.

**Comment by soarhevn** [comment]
Merged Pull request for this issue: Questionnaire UI layout and functions #30
