### ISSUE TITLE
Primary Election Losers still showing

### ISSUE THREAD

**Issue by soarhevn** [ACTtaiwan/CongressionalGuide#42]
Candidates who lose in the primary election are still showing in the list. For example, in Washington State 8, only Patty Murray and Chris Vance should show for Senate, and for House, only Dave Reichert & Tony Ventrella should show. For Oregon, only 3 should show for Senate, only 2 should show.

**Comment by balamark** [comment]
yea, those candidates are the outdated data in the original db. I will add an extra column indicate the candidate source then @terry77228 might need to adjust the front end code a bit.

**Comment by soarhevn** [comment]
Not sure how the candidate source will solve this issue. We need to show only those who won the primary election, that have the green checkmark next to their name in ballotpedia.

**Comment by soarhevn** [comment]
Add field in the DB to show if candidate is a winner of the primary. Field should be called "gen_election_candidate". As long as the field shows if a candidate is a primary winner, then we can use this to show the correct candidates on the front end.

Also need to grab and store in the DB if the candidate is the incumbent [currently import_candidates.py has incumbent=(False,)]

**Comment by soarhevn** [comment]
Mark, Can you improve the scrappy readme so a new user can understand it. Also perhaps mention it in the STARTHERE.md. Thanks

update: I already did this and will submit a pull request.
