### ISSUE TITLE
Fetch congressional district by address

### ISSUE THREAD

**Issue by soarhevn** [ACTtaiwan/CongressionalGuide#5]
If a user inputs a street address, need to look up the congressional district.

Use the USG Census server API at https://www.census.gov/data/developers/data-sets/Geocoding-services.html. Look for a return field of "cd114"

We will need to register for the API; but should not include the API key in the code on GitHub. Create as runtime variable.

**Comment by jtsaich** [comment]
There was code from 2014 using combination of texas AMU geocode service and sunlight district lookup service

**Comment by soarhevn** [comment]
This should be working fine.
