### ISSUE TITLE
Fetch candidate details

### ISSUE THREAD

**Issue by soarhevn** [ACTtaiwan/CongressionalGuide#6]
Once we have a state and district, need to fetch the candidate details. Most likely from Ballotpedia: <https://ballotpedia.org> - Candidates are /[name] i.e. https://ballotpedia.org/Ron_Crumpton
- What we used in V1: <http://www.politics1.com/>

## Info Needed
* Bio picture
* Name (show incumbent/challenger during election time)
* Party and district
* Email (if we can get it)
* Website, social media link (Facebook/Twitter)
* Notes section (information provide by us, maybe blank)
* Supported Taiwan bills (only show for incumbents)

## Web Scrapers
We will likely again have to scrape webpages again to get the info we need. Below are open source web scrapers.
* https://github.com/scrapinghub
* http://scrapy.org

**Comment by richmengsix** [comment]
If we want to use https://ballotpedia.org as the data source, we need to add a task to reverse engineer and write a valid name mapper to map the name stored in our database to the url format in ballotpedia.

**Comment by soarhevn** [comment]
@richmengsix I've created a new task for the name mapping at #17 

Will you be able to work on this?

**Comment by balamark** [comment]
I have a working Scrapy script that crawls all candidate's info from ballotpedia.org. Scrapy conveniently provides a way to get the output in json file: `"scrapy crawl test -o items.json"` This way, we just need to dump this into our database and have front end to display them. Let me clean up the code a bit and commit this.

**Comment by balamark** [comment]
This is what the json file looks like for each candidate:

`{"pic": "https://ballotpedia.org/wiki/images/thumb/0/0d/Scott_Stafne.jpg/200px-Scott_Stafne.jpg", "dist": "1st", "name": "Scott Stafne", "url": "https://ballotpedia.org/Scott_Stafne", "twtr": "https://twitter.com/Stafne4Congress", "camp": "http://www.stafne4congress.com/", "fb": "https://www.facebook.com/ScottStafne"}`

**Comment by soarhevn** [comment]
Nice!

**Comment by soarhevn** [comment]
Any ETA on completion?

**Comment by balamark** [comment]
sorry, just submit the pull request for the script. 
It took 2m47.375s on my laptop to crawl result back to item.json with size 695k. Should I submit another pull request for this file?

**Comment by richmengsix** [comment]
I pushed my code change to integrate w/ sunlight + introduce updated schema to the branch "legislatorInfoFromSunLight".
